---
sudo: required
dist: trusty

language: python
python: "2.7"

# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.4.0.0
  - ANSIBLE_VERSION=2.3.0.0
  - ANSIBLE_VERSION=2.2.0.0
  - ANSIBLE_VERSION=2.1.0.0
before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
  - ansible-galaxy install AdopteUnOps.rancher-install-cli
  - curl -L https://github.com/rancher/cli/releases/download/v0.6.4/rancher-linux-amd64-v0.6.4.tar.gz | tar zx --strip-components 2 -C /usr/local/bin"
script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  # Run the role/playbook with ansible-playbook.
  # dry run
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo --check
  # Run the role/playbook again, checking to make sure it's idempotent.
  #- >
  #  ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
  #  | grep -q 'changed=0.*failed=0'
  #  && (echo 'Idempotence test: pass' && exit 0)
  #  || (echo 'Idempotence test: fail' && exit 1)

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
